### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by maelle** [abresler/markovifyR#2]
Nice package, thank you!

It might make sense to have the Python installation instruction under the installation header?

**Comment by abresler** [comment]
That is a complicated OS specific problem and there is enough documentation on how to do that easily with a basic google search.

**Comment by maelle** [comment]
Oh I think I wasn't clear, what I meant is that your text"This package requires Python and markovify to be installed.

To install markovify in R you can run:" could go under the "Installation" header. Sorry! :-)
