### ISSUE TITLE
Readme error: could not find function "future_map_dfr"

### ISSUE THREAD

**Issue by goldingn** [abresler/markovifyR#5]
Running the readme example I get the error:
> ```
> Error in future_map_dfr(., function(x) { : 
>   could not find function "future_map_dfr"
> ```

The function `future_map_dfr` is called [here](https://github.com/abresler/markovifyR/blob/5989666f9a20b74950e5033ce32ce510af27ac60/R/markovify.R#L95) and [here](https://github.com/abresler/markovifyR/blob/5989666f9a20b74950e5033ce32ce510af27ac60/R/markovify.R#L142) but doesn't appear to be in the package or any dependencies.

I'm guessing markovifyr is just missing a dependency on `furrr`, which has a function by this name. The readme code works if I install and load `furrr`.

**Comment by abresler** [comment]
Correct or just update the packsge
